/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RecordingKitRouteImport } from './routes/recording-kit'
import { Route as ContributeRouteImport } from './routes/contribute'
import { Route as BrowseRouteImport } from './routes/browse'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StoriesStorySlugRouteImport } from './routes/stories/$storySlug'
import { Route as PoliciesPolicySlugRouteImport } from './routes/policies/$policySlug'
import { Route as ArticlesSlugRouteImport } from './routes/articles/$slug'
import { Route as ArchiveArchiveIdRouteImport } from './routes/archive/$archiveId'
import { Route as ApiSubmissionsRouteImport } from './routes/api/submissions'
import { Route as ApiArchiveArchiveIdRouteImport } from './routes/api/archive/$archiveId'
import { Route as ApiEditorSubmissionsMaintenanceRouteImport } from './routes/api/editor/submissions/maintenance'
import { Route as ApiEditorSubmissionsSubmissionIdRouteImport } from './routes/api/editor/submissions/$submissionId'
import { Route as ApiEditorSubmissionsSubmissionIdDispositionsRouteImport } from './routes/api/editor/submissions/$submissionId/dispositions'

const RecordingKitRoute = RecordingKitRouteImport.update({
  id: '/recording-kit',
  path: '/recording-kit',
  getParentRoute: () => rootRouteImport,
} as any)
const ContributeRoute = ContributeRouteImport.update({
  id: '/contribute',
  path: '/contribute',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseRoute = BrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesStorySlugRoute = StoriesStorySlugRouteImport.update({
  id: '/stories/$storySlug',
  path: '/stories/$storySlug',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliciesPolicySlugRoute = PoliciesPolicySlugRouteImport.update({
  id: '/policies/$policySlug',
  path: '/policies/$policySlug',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesSlugRoute = ArticlesSlugRouteImport.update({
  id: '/articles/$slug',
  path: '/articles/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchiveArchiveIdRoute = ArchiveArchiveIdRouteImport.update({
  id: '/archive/$archiveId',
  path: '/archive/$archiveId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSubmissionsRoute = ApiSubmissionsRouteImport.update({
  id: '/api/submissions',
  path: '/api/submissions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiArchiveArchiveIdRoute = ApiArchiveArchiveIdRouteImport.update({
  id: '/api/archive/$archiveId',
  path: '/api/archive/$archiveId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEditorSubmissionsMaintenanceRoute =
  ApiEditorSubmissionsMaintenanceRouteImport.update({
    id: '/api/editor/submissions/maintenance',
    path: '/api/editor/submissions/maintenance',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiEditorSubmissionsSubmissionIdRoute =
  ApiEditorSubmissionsSubmissionIdRouteImport.update({
    id: '/api/editor/submissions/$submissionId',
    path: '/api/editor/submissions/$submissionId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiEditorSubmissionsSubmissionIdDispositionsRoute =
  ApiEditorSubmissionsSubmissionIdDispositionsRouteImport.update({
    id: '/dispositions',
    path: '/dispositions',
    getParentRoute: () => ApiEditorSubmissionsSubmissionIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/browse': typeof BrowseRoute
  '/contribute': typeof ContributeRoute
  '/recording-kit': typeof RecordingKitRoute
  '/api/submissions': typeof ApiSubmissionsRoute
  '/archive/$archiveId': typeof ArchiveArchiveIdRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/policies/$policySlug': typeof PoliciesPolicySlugRoute
  '/stories/$storySlug': typeof StoriesStorySlugRoute
  '/api/archive/$archiveId': typeof ApiArchiveArchiveIdRoute
  '/api/editor/submissions/$submissionId': typeof ApiEditorSubmissionsSubmissionIdRouteWithChildren
  '/api/editor/submissions/maintenance': typeof ApiEditorSubmissionsMaintenanceRoute
  '/api/editor/submissions/$submissionId/dispositions': typeof ApiEditorSubmissionsSubmissionIdDispositionsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/browse': typeof BrowseRoute
  '/contribute': typeof ContributeRoute
  '/recording-kit': typeof RecordingKitRoute
  '/api/submissions': typeof ApiSubmissionsRoute
  '/archive/$archiveId': typeof ArchiveArchiveIdRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/policies/$policySlug': typeof PoliciesPolicySlugRoute
  '/stories/$storySlug': typeof StoriesStorySlugRoute
  '/api/archive/$archiveId': typeof ApiArchiveArchiveIdRoute
  '/api/editor/submissions/$submissionId': typeof ApiEditorSubmissionsSubmissionIdRouteWithChildren
  '/api/editor/submissions/maintenance': typeof ApiEditorSubmissionsMaintenanceRoute
  '/api/editor/submissions/$submissionId/dispositions': typeof ApiEditorSubmissionsSubmissionIdDispositionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/browse': typeof BrowseRoute
  '/contribute': typeof ContributeRoute
  '/recording-kit': typeof RecordingKitRoute
  '/api/submissions': typeof ApiSubmissionsRoute
  '/archive/$archiveId': typeof ArchiveArchiveIdRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/policies/$policySlug': typeof PoliciesPolicySlugRoute
  '/stories/$storySlug': typeof StoriesStorySlugRoute
  '/api/archive/$archiveId': typeof ApiArchiveArchiveIdRoute
  '/api/editor/submissions/$submissionId': typeof ApiEditorSubmissionsSubmissionIdRouteWithChildren
  '/api/editor/submissions/maintenance': typeof ApiEditorSubmissionsMaintenanceRoute
  '/api/editor/submissions/$submissionId/dispositions': typeof ApiEditorSubmissionsSubmissionIdDispositionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/browse'
    | '/contribute'
    | '/recording-kit'
    | '/api/submissions'
    | '/archive/$archiveId'
    | '/articles/$slug'
    | '/policies/$policySlug'
    | '/stories/$storySlug'
    | '/api/archive/$archiveId'
    | '/api/editor/submissions/$submissionId'
    | '/api/editor/submissions/maintenance'
    | '/api/editor/submissions/$submissionId/dispositions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/browse'
    | '/contribute'
    | '/recording-kit'
    | '/api/submissions'
    | '/archive/$archiveId'
    | '/articles/$slug'
    | '/policies/$policySlug'
    | '/stories/$storySlug'
    | '/api/archive/$archiveId'
    | '/api/editor/submissions/$submissionId'
    | '/api/editor/submissions/maintenance'
    | '/api/editor/submissions/$submissionId/dispositions'
  id:
    | '__root__'
    | '/'
    | '/browse'
    | '/contribute'
    | '/recording-kit'
    | '/api/submissions'
    | '/archive/$archiveId'
    | '/articles/$slug'
    | '/policies/$policySlug'
    | '/stories/$storySlug'
    | '/api/archive/$archiveId'
    | '/api/editor/submissions/$submissionId'
    | '/api/editor/submissions/maintenance'
    | '/api/editor/submissions/$submissionId/dispositions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BrowseRoute: typeof BrowseRoute
  ContributeRoute: typeof ContributeRoute
  RecordingKitRoute: typeof RecordingKitRoute
  ApiSubmissionsRoute: typeof ApiSubmissionsRoute
  ArchiveArchiveIdRoute: typeof ArchiveArchiveIdRoute
  ArticlesSlugRoute: typeof ArticlesSlugRoute
  PoliciesPolicySlugRoute: typeof PoliciesPolicySlugRoute
  StoriesStorySlugRoute: typeof StoriesStorySlugRoute
  ApiArchiveArchiveIdRoute: typeof ApiArchiveArchiveIdRoute
  ApiEditorSubmissionsSubmissionIdRoute: typeof ApiEditorSubmissionsSubmissionIdRouteWithChildren
  ApiEditorSubmissionsMaintenanceRoute: typeof ApiEditorSubmissionsMaintenanceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/recording-kit': {
      id: '/recording-kit'
      path: '/recording-kit'
      fullPath: '/recording-kit'
      preLoaderRoute: typeof RecordingKitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contribute': {
      id: '/contribute'
      path: '/contribute'
      fullPath: '/contribute'
      preLoaderRoute: typeof ContributeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse': {
      id: '/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof BrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories/$storySlug': {
      id: '/stories/$storySlug'
      path: '/stories/$storySlug'
      fullPath: '/stories/$storySlug'
      preLoaderRoute: typeof StoriesStorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policies/$policySlug': {
      id: '/policies/$policySlug'
      path: '/policies/$policySlug'
      fullPath: '/policies/$policySlug'
      preLoaderRoute: typeof PoliciesPolicySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/$slug': {
      id: '/articles/$slug'
      path: '/articles/$slug'
      fullPath: '/articles/$slug'
      preLoaderRoute: typeof ArticlesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archive/$archiveId': {
      id: '/archive/$archiveId'
      path: '/archive/$archiveId'
      fullPath: '/archive/$archiveId'
      preLoaderRoute: typeof ArchiveArchiveIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/submissions': {
      id: '/api/submissions'
      path: '/api/submissions'
      fullPath: '/api/submissions'
      preLoaderRoute: typeof ApiSubmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/archive/$archiveId': {
      id: '/api/archive/$archiveId'
      path: '/api/archive/$archiveId'
      fullPath: '/api/archive/$archiveId'
      preLoaderRoute: typeof ApiArchiveArchiveIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/editor/submissions/maintenance': {
      id: '/api/editor/submissions/maintenance'
      path: '/api/editor/submissions/maintenance'
      fullPath: '/api/editor/submissions/maintenance'
      preLoaderRoute: typeof ApiEditorSubmissionsMaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/editor/submissions/$submissionId': {
      id: '/api/editor/submissions/$submissionId'
      path: '/api/editor/submissions/$submissionId'
      fullPath: '/api/editor/submissions/$submissionId'
      preLoaderRoute: typeof ApiEditorSubmissionsSubmissionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/editor/submissions/$submissionId/dispositions': {
      id: '/api/editor/submissions/$submissionId/dispositions'
      path: '/dispositions'
      fullPath: '/api/editor/submissions/$submissionId/dispositions'
      preLoaderRoute: typeof ApiEditorSubmissionsSubmissionIdDispositionsRouteImport
      parentRoute: typeof ApiEditorSubmissionsSubmissionIdRoute
    }
  }
}

interface ApiEditorSubmissionsSubmissionIdRouteChildren {
  ApiEditorSubmissionsSubmissionIdDispositionsRoute: typeof ApiEditorSubmissionsSubmissionIdDispositionsRoute
}

const ApiEditorSubmissionsSubmissionIdRouteChildren: ApiEditorSubmissionsSubmissionIdRouteChildren =
  {
    ApiEditorSubmissionsSubmissionIdDispositionsRoute:
      ApiEditorSubmissionsSubmissionIdDispositionsRoute,
  }

const ApiEditorSubmissionsSubmissionIdRouteWithChildren =
  ApiEditorSubmissionsSubmissionIdRoute._addFileChildren(
    ApiEditorSubmissionsSubmissionIdRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BrowseRoute: BrowseRoute,
  ContributeRoute: ContributeRoute,
  RecordingKitRoute: RecordingKitRoute,
  ApiSubmissionsRoute: ApiSubmissionsRoute,
  ArchiveArchiveIdRoute: ArchiveArchiveIdRoute,
  ArticlesSlugRoute: ArticlesSlugRoute,
  PoliciesPolicySlugRoute: PoliciesPolicySlugRoute,
  StoriesStorySlugRoute: StoriesStorySlugRoute,
  ApiArchiveArchiveIdRoute: ApiArchiveArchiveIdRoute,
  ApiEditorSubmissionsSubmissionIdRoute:
    ApiEditorSubmissionsSubmissionIdRouteWithChildren,
  ApiEditorSubmissionsMaintenanceRoute: ApiEditorSubmissionsMaintenanceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
